version: '2'

services:
  redis:
    image: 'bitnami/redis:4.0'
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  oracle:
    image: truevoly/oracle-12c
    restart: always
    ports:
      - 1521:1521
    volumes:
      - oracle_data:/u01/app/oracle
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  mysql_data:
  oracle_data:
  postgres_data:
